name: Upload Coda Pack

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload-coda-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Upload Coda Pack
        uses: siriusnottin/upload-coda-pack@v1.0.0
        with:
          codaApiToken: ${{ secrets.CODA_API_TOKEN }}
      - name: Release Coda Pack
        uses: siriusnottin/release-coda-pack@main
        with:
          codaApiToken: ${{ secrets.CODA_API_TOKEN }}
          notes: ${{ github.event.release.body || github.event.release.tag_name || 'Automated release' }}